"""specflow project-audit — Full-project health review (deterministic core).

The CLI command is the deterministic backend. The /specflow-audit SKILL
orchestrates the conversational flow and optional adversarial wing subagents.

Analysis axes:
  - Horizontal: per artifact type, internal consistency
  - Vertical: per top-level REQ, V-model thread coherence
  - Cross-cutting: consistency, completeness, baseline-drift, compliance, NFR, test-coverage

All checks are deterministic (zero LLM tokens). The SKILL layer adds optional
adversarial "wings" via prompt engineering.
"""

from __future__ import annotations

import hashlib
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

from specflow.commands import artifact_lint
from specflow.lib import artifacts as art_lib
from specflow.lib import baselines as baseline_lib
from specflow.lib import challenges as chl_lib
from specflow.lib import standards as standards_lib
from specflow.lib.display import RED, GREEN, YELLOW, CYAN, NC, BOLD
from specflow.lib.techniques import TechniqueFinding

_SEP = "─" * 58

# Cross-cutting concerns whose warn-severity findings are ACCOUNTING ONLY:
# surfaced in the report and printed for review, but excluded from the warn
# count that drives the exit-2 (warnings) code. Doctrine (BP-005/006:
# deterministic signals must be truthful, default to warning): a release gate
# generated by lib/adapters/github_actions.py runs `project-audit` WITHOUT
# continue-on-error, so a warn→exit-2 there is blocking in practice. An
# accounting lens (e.g. docs-staleness — prose that cites a dead artifact) must
# be able to tell the truth ("these docs are stale") without holding up a
# release. STRUCTURAL warns (coverage gaps, schema issues, orphan code, …) still
# escalate. Add a concern here only when its lens comment explicitly declares
# "accounting, not policing" / "never escalates".
_ACCOUNTING_CONCERNS: frozenset[str] = frozenset({
    "docs-staleness",
    # verification: test-linkage / verify-runner-contract gaps. Accounting, not
    # policing — never escalates: a STORY missing a UT link is a traceability
    # bookkeeping gap (the tests usually exist, unlinked), not a V-model hole.
    # The genuine structural gaps (missing ARCH/missing STORY) stay concern=
    # "completeness" and still escalate.
    "verification",
    # ac-coverage: REQ acceptance-criteria vs linked-test count. Accounting, not
    # policing — never escalates: an AC/test count mismatch is review-worthy
    # coverage prose, not a release blocker. The 3 no-ARCH warns and the
    # orphan-code warn remain structural either way.
    "ac-coverage",
    # ac-observability: REQ AC falsifiability (observable / aspirational /
    # unclassified). Accounting, not policing — never escalates: an aspirational
    # AC ("responds quickly") is review-worthy prose, not a release blocker, and
    # the lens reports counts at INFO precisely so a lexicon edge case can never
    # cry-wolf at warn level. The conjunction guardrail (lib/ac_quality.py) keeps
    # domain observables ("the relay energizes") UNCLASSIFIED, never aspirational.
    "ac-observability",
})


def _ts() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def _audit_dir(root: Path, ts: str) -> Path:
    """Path to one audit run's snapshot directory (caller creates it)."""
    return root / ".specflow" / "audits" / ts


def _cache_dir(root: Path) -> Path:
    """Path to the audit findings cache directory (caller creates it)."""
    return root / ".specflow" / "audits" / ".cache"


_AUD_OUTPUT_TYPES = frozenset({"challenge", "audit"})

# Cache generation (CHL-344 A0): bump whenever lens semantics change so cached
# replays can't shadow new logic — the generation is folded into every project
# fingerprint, so one bump invalidates every cache file repo-wide (a one-time
# full recompute; acceptable and honest). Deliberately NOT keyed on
# __version__: dogfood lens changes land mid-version and must invalidate
# replays too.
_CACHE_GENERATION = 1


def _project_fingerprint(artifacts: list[art_lib.Artifact]) -> str:
    source_fps = sorted(
        art.fingerprint or art_lib.compute_fingerprint(art.body)
        for art in artifacts
        if art.type not in _AUD_OUTPUT_TYPES
    )
    payload = f"gen{_CACHE_GENERATION}|" + "|".join(source_fps)
    return hashlib.sha256(payload.encode()).hexdigest()[:16]


def _load_cached_findings(cache_dir: Path, fingerprint: str) -> list[dict[str, str]]:
    path = cache_dir / f"{fingerprint}.md"
    if not path.exists():
        return []
    try:
        text = path.read_text(encoding="utf-8")
        if not text.strip().startswith("---"):
            return []
        end = text.find("---", 3)
        if end == -1:
            return []
        fm = yaml.safe_load(text[3:end])
        if isinstance(fm, dict):
            return fm.get("findings", [])
    except Exception:
        pass
    return []


def _save_cached_findings(cache_dir: Path, fingerprint: str, findings: list[dict[str, str]]) -> None:
    fm = {"fingerprint": fingerprint, "cached_at": _ts(), "findings": findings}
    content = "---\n" + yaml.dump(fm, default_flow_style=False, sort_keys=False) + "---\n"
    (cache_dir / f"{fingerprint}.md").write_text(content, encoding="utf-8")


def _apply_fingerprint_cache(
    artifacts: list[art_lib.Artifact], cache_dir: Path
) -> tuple[bool, list[dict[str, str]]]:
    proj_fp = _project_fingerprint(artifacts)
    cached = _load_cached_findings(cache_dir, proj_fp)
    if cached:
        return True, cached
    return False, []


def _horizontal_analysis(artifacts: list[art_lib.Artifact]) -> dict[str, list[dict[str, str]]]:
    findings: dict[str, list[dict[str, str]]] = {}
    by_type: dict[str, list[art_lib.Artifact]] = {}
    for art in artifacts:
        by_type.setdefault(art.type, []).append(art)

    for type_name, arts in sorted(by_type.items()):
        items: list[dict[str, str]] = []
        statuses = [a.status for a in arts]
        status_counts: dict[str, int] = {}
        for s in statuses:
            status_counts[s] = status_counts.get(s, 0) + 1

        if len(status_counts) == 1 and "draft" in status_counts:
            items.append({
                "severity": "info",
                "message": f"All {len(arts)} {type_name} artifacts are in draft",
            })

        # "No links" counts artifacts with no provenance at all. Research types
        # (EXPT/LOOP/FIND/COMP) carry provenance in frontmatter fields, not
        # links[]; has_provenance recognizes both so autoresearch-heavy projects
        # don't get a headline "97/104 EXPT have no links" that is just noise.
        orphan_count = sum(1 for a in arts if not art_lib.has_provenance(a))
        if orphan_count > len(arts) // 2 and len(arts) > 2:
            items.append({
                "severity": "warn",
                "message": f"{orphan_count}/{len(arts)} {type_name} artifacts have no links/provenance",
            })

        tags_used: set[str] = set()
        for a in arts:
            tags_used.update(a.tags or [])
        if not tags_used and len(arts) > 3:
            items.append({
                "severity": "info",
                "message": f"No {type_name} artifacts use tags",
            })

        if items:
            findings[type_name] = items
    return findings


def _vertical_analysis(artifacts: list[art_lib.Artifact]) -> list[dict[str, str]]:
    findings: list[dict[str, str]] = []
    id_index = art_lib.build_id_index(artifacts)

    top_reqs = [
        a for a in artifacts
        if art_lib.get_prefix_from_id(a.id) == "REQ"
        and "." not in a.id
        and a.status in ("approved", "implemented", "verified")
    ]

    for req in top_reqs:
        thread_arts: list[str] = [req.id]
        thread_links: dict[str, str] = {}

        for other in artifacts:
            for link in other.links:
                if link.target == req.id and link.role in ("refined_by", "derives_from"):
                    if art_lib.get_prefix_from_id(other.id) == "ARCH":
                        thread_arts.append(other.id)
                        thread_links[other.id] = req.id

        for other in artifacts:
            for link in other.links:
                if link.target in thread_arts and link.role in ("refined_by", "derives_from"):
                    if art_lib.get_prefix_from_id(other.id) == "DDD":
                        thread_arts.append(other.id)
                        thread_links[other.id] = link.target

        story_ids: list[str] = []
        for other in artifacts:
            for link in other.links:
                if link.target in thread_arts and link.role == "implements":
                    if art_lib.get_prefix_from_id(other.id) == "STORY":
                        story_ids.append(other.id)
                        thread_arts.append(other.id)

        has_arch = any(art_lib.get_prefix_from_id(a) == "ARCH" for a in thread_arts)
        has_ddd = any(art_lib.get_prefix_from_id(a) == "DDD" for a in thread_arts)
        has_stories = len(story_ids) > 0

        if not has_arch:
            findings.append({
                "severity": "warn",
                "message": f"{req.id}: no ARCH refinement in V-model thread",
            })
        if not has_ddd and has_arch:
            findings.append({
                "severity": "warn",
                "message": f"{req.id}: ARCH exists but no DDD refinement",
            })
        if not has_stories:
            findings.append({
                "severity": "warn",
                "message": f"{req.id}: no STORY implements this requirement",
            })

        for story_id in story_ids:
            has_verification = False
            for other in artifacts:
                for link in other.links:
                    if link.target == story_id and link.role == "verified_by":
                        has_verification = True
                        break
                if has_verification:
                    break
            if not has_verification:
                findings.append({
                    "severity": "warn",
                    # Accounting, not policing — never escalates: a STORY with no
                    # verified_by test link is a traceability bookkeeping gap
                    # (the tests usually exist, unlinked), not a V-model hole.
                    # Real V-model gaps (no ARCH / no STORY) have NO concern and
                    # still escalate above.
                    "concern": "verification",
                    "message": f"{story_id} (implements {req.id}): no test verification",
                })

    return findings


def _resolve_drift_pair(
    root: Path, baseline_anchor: str | None
) -> tuple[list[str], str | None]:
    """Resolve the baseline-drift comparison pair for this run.

    Returns ``(pair, warning)``. Without an anchor the pair is the
    semver-preferring auto pair (``select_release_pair``). With ``--baseline``:
    a known name anchors drift as <baseline> → newest semver release (falling
    back to the newest baseline overall when nothing parses as semver); an
    unknown name warns and falls back to the auto pair — accounting, not
    policing, so a typo never fails the audit.
    """
    baselines = baseline_lib.list_baselines(root)
    pair = baseline_lib.select_release_pair(baselines)
    anchor = (baseline_anchor or "").strip()
    if not anchor:
        return pair, None
    if baseline_lib.load_baseline(root, anchor) is None:
        return pair, (
            f"--baseline '{anchor}' not found among "
            f"{len(baselines)} baseline(s); falling back to the auto pair"
        )
    newest = baseline_lib.newest_release(baselines) or (
        baselines[-1] if baselines else anchor
    )
    return [anchor, newest], None


def _cross_cutting_analysis(
    artifacts: list[art_lib.Artifact],
    root: Path,
    drift_pair: list[str] | None = None,
) -> dict[str, list[dict[str, str]]]:
    results: dict[str, list[dict[str, str]]] = {}

    # Coverage split (BP-005/006 accounting carve-out): check_coverage now
    # separates STRUCTURAL gaps (missing ARCH / missing STORY — genuine V-model
    # holes, stay escalating under concern="completeness") from TEST-VERIFICATION
    # gaps (a STORY implemented with no UT/IT/QT linked via verified_by — a
    # linkage bookkeeping gap, accounting under concern="verification"). The two
    # rolled warns land in different concern buckets so the exit gate can keep
    # the structural ones blocking while the test-linkage ones never drive exit-2.
    lint_result = artifact_lint.check_coverage(artifacts)
    struct_n = int(lint_result.get("structural_warning_count", 0))
    verif_n = int(lint_result.get("verification_warning_count", 0))
    if struct_n > 0:
        results.setdefault("completeness", []).append({
            "severity": "warn",
            "concern": "completeness",
            "message": (
                f"{struct_n} structural coverage gap(s): "
                f"{lint_result.get('structural_detail', '')[:200]}"
            ),
        })
    if verif_n > 0:
        results.setdefault("verification", []).append({
            "severity": "warn",
            "concern": "verification",
            "message": (
                f"{verif_n} test-verification coverage gap(s): "
                f"{lint_result.get('verification_detail', '')[:200]}"
            ),
        })

    baseline_findings: list[dict[str, str]] = []
    if drift_pair is None:
        drift_pair = baseline_lib.select_release_pair(
            baseline_lib.list_baselines(root)
        )
    if len(drift_pair) >= 2:
        diff = baseline_lib.diff_baselines(root, drift_pair[0], drift_pair[1])
        if diff.get("ok"):
            for sc in diff.get("status_changed", []):
                baseline_findings.append({
                    "severity": "info",
                    "message": f"{sc['id']}: status {sc['old']} → {sc['new']}",
                })
            for fp in diff.get("fingerprint_changed", []):
                baseline_findings.append({
                    "severity": "info",
                    "message": f"{fp['id']}: content changed (fingerprint drift)",
                })
            for rm in diff.get("removed", []):
                baseline_findings.append({
                    "severity": "warn",
                    "message": f"{rm['id']}: removed since last baseline",
                })
    if baseline_findings:
        results["baseline-drift"] = baseline_findings

    compliance_findings: list[dict[str, str]] = []
    comp = standards_lib.check_compliance(root)
    if comp.get("ok"):
        uncovered = comp.get("uncovered", [])
        if uncovered:
            compliance_findings.append({
                "severity": "warn",
                "message": f"{len(uncovered)}/{comp['total_clauses']} clauses uncovered in {comp['standard']}",
            })
        else:
            compliance_findings.append({
                "severity": "info",
                "message": f"All {comp['total_clauses']} clauses covered ({comp['standard']})",
            })
    if compliance_findings:
        results["standards-coverage"] = compliance_findings

    nfr_findings: list[dict[str, str]] = []
    reqs = [a for a in artifacts if art_lib.get_prefix_from_id(a.id) == "REQ"]
    nfr_cats: dict[str, int] = {}
    nfr_missing = 0
    for req in reqs:
        cat = req.frontmatter.get("non_functional_category", "")
        if cat:
            nfr_cats[cat] = nfr_cats.get(cat, 0) + 1
        else:
            nfr_missing += 1
    if nfr_missing > 0 and len(reqs) > 0:
        pct = nfr_missing * 100 // len(reqs)
        nfr_findings.append({
            "severity": "info" if pct < 50 else "warn",
            "message": f"{nfr_missing}/{len(reqs)} REQs have no non_functional_category",
        })
    if nfr_cats:
        categories_str = ", ".join(f"{k}({v})" for k, v in sorted(nfr_cats.items()))
        nfr_findings.append({
            "severity": "info",
            "message": f"NFR categories: {categories_str}",
        })
    if nfr_findings:
        results["nfr-coverage"] = nfr_findings

    schema_dir = root / ".specflow" / "schema"
    schema_result = artifact_lint.check_schema(artifacts, schema_dir)
    consistency_findings: list[dict[str, str]] = []
    if schema_result["blocking_count"] > 0:
        consistency_findings.append({"severity": "error", "message": f"{schema_result['blocking_count']} schema issue(s)"})
    if schema_result["warning_count"] > 0:
        consistency_findings.append({"severity": "warn", "message": f"{schema_result['warning_count']} schema warning(s)"})
    if consistency_findings:
        results["consistency"] = consistency_findings

    # Orphan source-code lens: source files not traced to any STORY/REQ via
    # output_files. Surfaces the dormant `detect orphan-code` scan in the audit.
    # Distinguishes "tracking not adopted" (info) from "files slipped through
    # partial tracking" (warn) to avoid alarm fatigue.
    orphan_findings: list[dict[str, str]] = []
    try:
        from specflow.lib.orphans import find_orphan_code

        oc = find_orphan_code(root)
        total = oc["total_count"]
        referenced = oc["referenced_count"]
        orphan_n = len(oc["orphan_files"])
        if total > 0:
            if referenced == 0 and orphan_n > 0:
                orphan_findings.append({
                    "severity": "info",
                    "message": (
                        f"Source↔spec tracking not in use: 0/{total} source files linked to a "
                        f"STORY/REQ via output_files. Run `specflow detect orphan-code`."
                    ),
                })
            elif orphan_n > 0:
                orphan_findings.append({
                    "severity": "warn",
                    "message": (
                        f"{orphan_n}/{total} source files orphaned (not traced to any STORY/REQ). "
                        f"Run `specflow detect orphan-code` (adopt with --retro-link)."
                    ),
                })
            else:
                orphan_findings.append({
                    "severity": "info",
                    "message": f"All {total} source files traced to a STORY/REQ.",
                })
    except Exception:
        pass
    if orphan_findings:
        results["orphan-code"] = orphan_findings

    # Docs-staleness lens: docs that cite a superseded/cancelled/deprecated
    # artifact. Accounting, not policing: findings are surfaced for review but
    # never escalate the exit code — "docs-staleness" is registered in
    # _ACCOUNTING_CONCERNS, so its warns are excluded from the exit-2 count.
    # Docs are prose; staleness is reported, never enforced (BP-005/006).
    docs_findings: list[dict[str, str]] = []
    try:
        from specflow.lib import docs as docs_lib

        docs = docs_lib.discover_docs(root)
        stale = docs_lib.check_stale(root, docs, artifacts)
        for s in stale:
            docs_findings.append({"severity": "warn", "message": s["message"]})
        if docs and not stale:
            docs_findings.append({
                "severity": "info",
                "message": f"{len(docs)} doc(s) scanned; all citations current.",
            })
    except Exception:
        pass
    if docs_findings:
        results["docs-staleness"] = docs_findings

    # Verification-contract lens (accounting, not policing — see
    # _verification_lens). Pure helper so the lens buckets are unit-testable
    # without running the full cross-cutting pipeline.
    verify_findings = _verification_lens(artifacts)
    if verify_findings:
        results.setdefault("verification", []).extend(verify_findings)

    # AC-coverage lens (accounting, not policing — see _ac_coverage_lens).
    ac_findings = _ac_coverage_lens(artifacts)
    if ac_findings:
        results.setdefault("ac-coverage", []).extend(ac_findings)

    # AC-observability lens (accounting, not policing — see
    # _ac_observability_lens). INFO-severity aggregate only — never a per-AC
    # warn, so lexicon edge cases cannot cry-wolf at warn level.
    ac_obs_findings = _ac_observability_lens(artifacts)
    if ac_obs_findings:
        results.setdefault("ac-observability", []).extend(ac_obs_findings)

    return results


def _verification_lens(artifacts: list[art_lib.Artifact]) -> list[dict[str, str]]:
    """Declared verify_command vs recorded verify_run_* results.

    Modeled on the orphan-code shape: not-adopted → info / declared-never-run /
    failed / drifted → warn / clean → info. Accounting, not policing — never
    escalates: "verification" is registered in ``_ACCOUNTING_CONCERNS``, so its
    warns never drive exit-2. The lens surfaces honest run-state signals
    (declared but never run, last run failed, command drifted since last run)
    for review without holding up a release on a contract/traceability
    bookkeeping gap (BP-005/006). Degrades gracefully — a project with zero
    verify_command anywhere → ONE info, never a warn.

    Reads implementer B's pinned fields (verify_command, verify_exit_code,
    verify_run_at, verify_run_exit_code, verify_run_command_hash) and never
    writes them.
    """
    findings: list[dict[str, str]] = []
    candidate_types = {"unit-test", "integration-test", "qualification-test", "story"}
    try:
        any_contract = any(art.frontmatter.get("verify_command") for art in artifacts)
        if not any_contract:
            findings.append({
                "severity": "info",
                "message": (
                    "Verification contracts not adopted: no artifact declares a "
                    "verify_command. Run `specflow verify` to record test-run evidence."
                ),
            })
            return findings
        declared = 0
        clean = 0
        for art in artifacts:
            if (art.type not in candidate_types
                    or art.status not in ("implemented", "verified")):
                continue
            cmd = art.frontmatter.get("verify_command")
            if not cmd:
                continue
            declared += 1
            run_at = art.frontmatter.get("verify_run_at")
            run_exit = art.frontmatter.get("verify_run_exit_code")
            expected_exit = art.frontmatter.get("verify_exit_code", 0)
            run_cmd_hash = art.frontmatter.get("verify_run_command_hash")
            # compute_fingerprint-style hash of the current command so a changed
            # verify_command is detectable against the stored run-command hash.
            current_hash = "sha256:" + hashlib.sha256(
                str(cmd).encode("utf-8")
            ).hexdigest()[:12]
            if not run_at:
                findings.append({
                    "severity": "warn",
                    "message": f"{art.id}: verify_command declared but never run",
                })
            elif run_exit is not None and str(run_exit) != str(expected_exit):
                findings.append({
                    "severity": "warn",
                    "message": f"{art.id}: last verify run failed (exit {run_exit})",
                })
            elif run_cmd_hash and run_cmd_hash != current_hash:
                findings.append({
                    "severity": "warn",
                    "message": f"{art.id}: verify_command drifted since last run",
                })
            else:
                clean += 1
        if declared and clean == declared:
            findings.append({
                "severity": "info",
                "message": (
                    f"{clean} artifact(s) declare verify_command; all have "
                    f"current, green verify runs."
                ),
            })
    except Exception:
        pass
    # Self-describing: stamp the accounting concern so _count_warns classifies
    # the lens output correctly even before run()'s bucket-level stamping.
    for f in findings:
        f["concern"] = "verification"
    return findings


def _ac_coverage_lens(artifacts: list[art_lib.Artifact]) -> list[dict[str, str]]:
    """REQ acceptance-criteria count vs linked-test count.

    Per implemented/verified REQ, count AC items (lint parsers) vs linked tests
    (QT direct; IT via ARCH; UT via ARCH→DDD — the rtm._children_of walk) and
    how many linked tests carry a green verify_run. Accounting, not policing —
    never escalates: "ac-coverage" is registered in ``_ACCOUNTING_CONCERNS``, so
    its warns never drive exit-2: a REQ whose AC count exceeds its linked-test
    count is a review-worthy coverage signal, not a release blocker (BP-005/006).

    Signals: REQ with ACs but ZERO linked tests → warn; linked-test-count <
    AC-count → info "count mismatch, review"; else clean.
    """
    findings: list[dict[str, str]] = []
    try:
        from specflow.commands.rtm import _children_of as _rtm_children
        from specflow.lib import lint as _lint

        decompose = {"derives_from", "refined_by"}
        ac_reqs = [
            a for a in artifacts
            if art_lib.get_prefix_from_id(a.id) == "REQ"
            and a.status in ("implemented", "verified")
        ]
        for req in ac_reqs:
            ac_count = _lint.count_acceptance_criteria_items(req)
            if ac_count == 0:
                continue
            # Linked-test walk: QT direct + IT via ARCH + UT via ARCH→DDD.
            qts = _rtm_children(req.id, "qualification-test", {"verified_by"}, artifacts)
            archs = _rtm_children(req.id, "architecture", decompose, artifacts)
            linked: list[art_lib.Artifact] = list(qts)
            for arch in archs:
                linked.extend(_rtm_children(arch.id, "integration-test", {"verified_by"}, artifacts))
                for ddd in _rtm_children(arch.id, "detailed-design", decompose, artifacts):
                    linked.extend(_rtm_children(ddd.id, "unit-test", {"verified_by"}, artifacts))
            # dedupe by id
            seen_ids: set[str] = set()
            uniq: list[art_lib.Artifact] = []
            for t in linked:
                if t.id not in seen_ids:
                    seen_ids.add(t.id)
                    uniq.append(t)
            test_count = len(uniq)
            green = 0
            for t in uniq:
                r_exit = t.frontmatter.get("verify_run_exit_code")
                e_exit = t.frontmatter.get("verify_exit_code", 0)
                if r_exit is not None and str(r_exit) == str(e_exit):
                    green += 1
            if test_count == 0:
                findings.append({
                    "severity": "warn",
                    "message": (
                        f"{req.id}: {ac_count} AC item(s) but no linked tests "
                        f"(QT/IT/UT via verified_by)"
                    ),
                })
            elif test_count < ac_count:
                findings.append({
                    "severity": "info",
                    "message": (
                        f"{req.id}: {test_count} linked test(s) < {ac_count} AC "
                        f"item(s) ({green} green) — review coverage"
                    ),
                })
    except Exception:
        pass
    # Self-describing: stamp the accounting concern (see _verification_lens).
    for f in findings:
        f["concern"] = "ac-coverage"
    return findings


def _ac_observability_lens(artifacts: list[art_lib.Artifact]) -> list[dict[str, str]]:
    """REQ acceptance-criteria observability (observable / aspirational / unclassified).

    Per REQ with ACs, report the per-REQ observability ratio and aspirational
    count. Modeled on ``_ac_coverage_lens`` but INFO-severity throughout —
    aspirational ACs surface as review-worthy counts, NEVER as per-AC warns,
    so a lexicon edge case cannot cry-wolf at warn level. Accounting, not
    policing — never escalates: "ac-observability" is registered in
    ``_ACCOUNTING_CONCERNS``, so even if a future caller stamped a warn it
    could not drive exit-2. The conjunction guardrail (lib/ac_quality.py)
    keeps domain observables ("the relay energizes") UNCLASSIFIED, never
    aspirational — that is what prevents this lens from discrediting itself on
    legitimate engineering ACs.

    Signals: every REQ with ACs → one INFO line ("REQ-001: 3/5 observable, 1
    aspirational, 1 unclassified"); a project-wide summary line when any
    aspirational ACs exist. Degrades gracefully — zero REQs/zero ACs → no
    findings (silence), never a warn.
    """
    findings: list[dict[str, str]] = []
    try:
        from specflow.lib import ac_quality

        agg = ac_quality.classify_reqs_observability(artifacts)
        if agg["reqs_with_acs"] == 0:
            return findings
        for r in sorted(agg["per_req"], key=lambda r: r["id"]):
            findings.append({
                "severity": "info",
                "message": (
                    f"{r['id']}: {r['observable']}/{r['total']} observable, "
                    f"{r['aspirational']} aspirational, {r['unclassified']} unclassified"
                ),
            })
        if agg["aspirational"] > 0:
            findings.append({
                "severity": "info",
                "message": (
                    f"Project: {agg['aspirational']} aspirational AC(s) across "
                    f"{agg['aspirational_reqs']} REQ(s); {agg['aspirational_free_reqs']}/"
                    f"{agg['reqs_with_acs']} REQ(s) aspirational-free "
                    f"({agg['observable']} observable, {agg['unclassified']} unclassified)"
                ),
            })
    except Exception:
        pass
    # Self-describing: stamp the accounting concern (see _verification_lens).
    for f in findings:
        f["concern"] = "ac-observability"
    return findings


def _sample_artifacts(
    artifacts: list[art_lib.Artifact], sample_pct: int
) -> list[art_lib.Artifact]:
    if sample_pct >= 100:
        return artifacts
    always_include = [
        a for a in artifacts
        if art_lib.get_prefix_from_id(a.id) in ("REQ", "ARCH")
    ]
    rest = [a for a in artifacts if a not in always_include]
    n = max(1, len(rest) * sample_pct // 100)
    sampled = sorted(rest, key=lambda a: int(hashlib.md5(a.id.encode()).hexdigest(), 16))[:n]
    return always_include + sampled


def _render_report(
    ts: str,
    horizontal: dict[str, list[dict[str, str]]],
    vertical: list[dict[str, str]],
    cross_cutting: dict[str, list[dict[str, str]]],
    cached_count: int,
    total_artifacts: int,
    scope_info: list[str],
    chain_coverage: tuple[int, int] | None = None,
    prior_audit: art_lib.Artifact | None = None,
) -> str:
    all_findings = _collect_all_findings(horizontal, vertical, cross_cutting)
    errors = sum(1 for f in all_findings if f["severity"] == "error")
    warns = sum(1 for f in all_findings if f["severity"] == "warn")
    infos = sum(1 for f in all_findings if f["severity"] == "info")
    warn_split = _count_warns(all_findings)  # (escalating, accounting), A1

    lines = [
        f"# Project Audit Report",
        f"",
        f"- **Timestamp**: {ts}",
        f"- **Artifacts analyzed**: {total_artifacts} (cached: {cached_count})",
    ]
    # Chain-coverage top-line metric + trend deltas vs the prior audit
    # (CHL-341 / CHL-344#2). Informational — never affects the exit code.
    # Rendered from the loaded artifact list, so it appears even when the
    # findings themselves come from the fingerprint cache.
    if chain_coverage is not None:
        cov_covered, cov_total = chain_coverage
        if cov_total > 0:
            cov_pct = round(cov_covered * 100 / cov_total)
            lines.append(
                f"- **Chain coverage**: {cov_pct}% ({cov_covered}/{cov_total} "
                f"approved STORYs fully covered by UT+IT+QT)"
            )
        else:
            cov_pct = -1
            lines.append("- **Chain coverage**: n/a (no approved STORYs)")
        lines.append(_trend_bullet(errors, warns, infos, cov_pct, prior_audit,
                                   cur_warn_split=warn_split))
    if scope_info:
        for s in scope_info:
            lines.append(f"- **{s}**")
    lines.append("")

    lines.append("## Horizontal Analysis (per artifact type)")
    lines.append("")
    if horizontal:
        for type_name, items in sorted(horizontal.items()):
            lines.append(f"### {type_name}")
            for item in items:
                icon = "✗" if item["severity"] == "error" else "⚠" if item["severity"] == "warn" else "○"
                lines.append(f"- [{icon}] {item['message']}")
            lines.append("")
    else:
        lines.append("No issues found across artifact types.")
        lines.append("")

    lines.append("## Vertical Analysis (V-model threads)")
    lines.append("")
    if vertical:
        for item in vertical:
            icon = "✗" if item["severity"] == "error" else "⚠" if item["severity"] == "warn" else "○"
            lines.append(f"- [{icon}] {item['message']}")
    else:
        lines.append("No V-model thread gaps found.")
    lines.append("")

    lines.append("## Cross-cutting Analysis")
    lines.append("")
    if cross_cutting:
        for concern, items in sorted(cross_cutting.items()):
            lines.append(f"### {concern}")
            for item in items:
                icon = "✗" if item["severity"] == "error" else "⚠" if item["severity"] == "warn" else "○"
                lines.append(f"- [{icon}] {item['message']}")
            lines.append("")
    else:
        lines.append("No cross-cutting issues found.")
        lines.append("")

    lines.append("## Summary")
    lines.append("")
    lines.append(f"| Severity | Count |")
    lines.append(f"|----------|-------|")
    lines.append(f"| Error    | {errors} |")
    lines.append(f"| Warning  | {warns} |")
    lines.append(f"| Info     | {infos} |")
    lines.append("")

    return "\n".join(lines)


def _collect_all_findings(
    horizontal: dict[str, list[dict[str, str]]],
    vertical: list[dict[str, str]],
    cross_cutting: dict[str, list[dict[str, str]]],
) -> list[dict[str, str]]:
    all_f: list[dict[str, str]] = []
    for items in horizontal.values():
        all_f.extend(items)
    all_f.extend(vertical)
    for items in cross_cutting.values():
        all_f.extend(items)
    return all_f


def _count_warns(findings: list[dict[str, str]]) -> tuple[int, int]:
    """Split warn-severity findings into (escalating, accounting) counts.

    Accounting warns (cross-cutting concern in ``_ACCOUNTING_CONCERNS``) are
    printed and reported but never drive the exit-2 code; every other warn is
    structural and escalates. Pure function so the escalation gate is unit-
    testable without running the full audit pipeline.
    """
    accounting = 0
    escalating = 0
    for f in findings:
        if f.get("severity") != "warn":
            continue
        if f.get("concern") in _ACCOUNTING_CONCERNS:
            accounting += 1
        else:
            escalating += 1
    return escalating, accounting


# Machine-readable summary fields stamped on every AUD artifact this command
# creates, so the NEXT audit can render honest trend deltas against this one
# (CHL-341 / CHL-344#2). chain_coverage_pct uses -1 as the n/a sentinel (no
# approved STORYs to measure).
#
# The A1 warn-split fields (summary_warns_escalating / summary_warns_accounting,
# CHL-344) are deliberately NOT in this tuple: _prior_audit_summary returns
# None whenever ANY field here is missing, which is the "predates summary
# stamping" fallback — adding the split here would demote every pre-A1 audit
# (AUD-073..080) from a full trend baseline to n/a. The split is stamped
# ALONGSIDE these fields and consumed opportunistically by _trend_bullet.
_SUMMARY_STAMP_FIELDS = ("summary_errors", "summary_warns", "summary_info", "chain_coverage_pct")


def _chain_coverage_stats(artifacts: list[art_lib.Artifact]) -> tuple[int, int]:
    """(covered, total) approved STORYs fully verified via UT+IT+QT links.

    Derived from ``artifact_lint.check_coverage``'s own approved-story walk
    (same predicate, same verified_by link scan), so the audit header metric
    and the lint coverage check can never disagree. Informational only — the
    numbers never feed the exit-code gate (accounting, not policing).
    """
    r = artifact_lint.check_coverage(artifacts)
    covered = int(r.get("approved_story_covered", 0))
    total = int(r.get("approved_story_total", 0))
    return covered, total


def _select_prior_audit(artifacts: list[art_lib.Artifact]) -> art_lib.Artifact | None:
    """The most recent PRIOR AUD artifact, or None.

    Ordered by ``created`` (falling back to ``modified`` when absent) because
    IDs alone lie: ledgers can carry OLD draft-ID audits (AUD-<hash>) that
    predate newer numbered ones, and same-day numbered audits are created in
    suffix order. Ties on the timestamp break by ID shape — numeric suffix
    first (higher suffix wins), then hash-suffix drafts by id — so a draft
    created the same day as the last numbered audit still sorts after it.
    Defensive: any parse failure yields None rather than a crash.
    """
    try:
        auds = [
            a for a in artifacts
            if a.type == "audit" or art_lib.get_prefix_from_id(a.id) == "AUD"
        ]
        if not auds:
            return None

        def _key(a: art_lib.Artifact) -> tuple[str, int, int, str]:
            when = str(a.frontmatter.get("created") or a.frontmatter.get("modified") or "")
            suffix = a.id.rsplit("-", 1)[-1]
            try:
                return (when, 0, int(suffix), a.id)
            except ValueError:
                return (when, 1, 0, a.id)

        return max(auds, key=_key)
    except Exception:
        return None


def _prior_audit_summary(art: art_lib.Artifact) -> dict[str, int] | None:
    """The stamped summary fields of a prior AUD as ints, or None when the
    artifact predates summary stamping (or its fields are unparseable)."""
    fm = art.frontmatter
    if any(k not in fm for k in _SUMMARY_STAMP_FIELDS):
        return None
    try:
        return {k: int(fm[k]) for k in _SUMMARY_STAMP_FIELDS}
    except (TypeError, ValueError):
        return None


def _prior_warn_split(art: art_lib.Artifact) -> tuple[int, int] | None:
    """(escalating, accounting) warn split stamped on a prior AUD (A1), or
    None when the artifact predates the split stamp or either field is
    missing/unparseable. Deliberately separate from _prior_audit_summary:
    a prior lacking ONLY the split is still a full trend baseline — the
    trend line degrades to legacy total rendering, never to "predates
    summary stamping" and never to invented split numbers."""
    fm = art.frontmatter
    try:
        return (int(fm["summary_warns_escalating"]),
                int(fm["summary_warns_accounting"]))
    except (KeyError, TypeError, ValueError):
        return None


def _signed_delta(d: int) -> str:
    """Signed delta rendering: 0 → "0", positive → "+N", negative → "−N"."""
    if d == 0:
        return "0"
    return f"+{d}" if d > 0 else f"−{abs(d)}"


def _trend_bullet(
    cur_errors: int,
    cur_warns: int,
    cur_infos: int,
    cur_pct: int,
    prior: art_lib.Artifact | None,
    cur_warn_split: tuple[int, int] | None = None,
) -> str:
    """Header trend line vs the prior audit (CHL-341). ``cur_pct`` is -1 when
    the current run has no approved STORYs (n/a). Pure rendering from loaded
    data — read-only, never affects the exit code, safe under --dry-run and
    fingerprint-cache hits alike.

    ``cur_warn_split`` is the current run's (escalating, accounting) warn
    split (A1, CHL-344). The warns bullet is extended with the split ONLY
    when both the current run and the prior AUD carry it — otherwise the
    legacy total-only rendering stays exactly as before."""
    if prior is None:
        return "- **Trend**: first audit — no prior baseline"
    prev = _prior_audit_summary(prior)
    if prev is None:
        return f"- **Trend vs {prior.id}**: n/a (prior audit predates summary stamping)"
    warn_part = (
        f"warns {prev['summary_warns']}→{cur_warns} "
        f"(Δ{_signed_delta(cur_warns - prev['summary_warns'])})"
    )
    prev_split = _prior_warn_split(prior)
    if cur_warn_split is not None and prev_split is not None:
        cur_esc, cur_acc = cur_warn_split
        prev_esc, prev_acc = prev_split
        warn_part += f" (escalating {prev_esc}→{cur_esc}, accounting {prev_acc}→{cur_acc})"
    parts = [
        f"errors {prev['summary_errors']}→{cur_errors} "
        f"(Δ{_signed_delta(cur_errors - prev['summary_errors'])})",
        warn_part,
        f"info {prev['summary_info']}→{cur_infos} "
        f"(Δ{_signed_delta(cur_infos - prev['summary_info'])})",
    ]
    if cur_pct >= 0 and prev["chain_coverage_pct"] >= 0:
        parts.append(
            f"chain coverage {prev['chain_coverage_pct']}%→{cur_pct}% "
            f"(Δ{_signed_delta(cur_pct - prev['chain_coverage_pct'])} pp)"
        )
    else:
        parts.append("chain coverage n/a (no approved STORYs)")
    return f"- **Trend vs {prior.id}**: " + ", ".join(parts)


def _artifact_scope(f: dict[str, str]) -> str:
    """Best-effort scope label for a finding's CHL-table row: its artifact type
    (horizontal) or concern (cross-cutting), else a dash. Findings carry no
    per-artifact id — horizontal findings are per-type aggregates, so type or
    concern is the finest honest scope available."""
    return f.get("type") or f.get("concern") or "—"


# Maps each audit axis to the thinking-technique tag stamped on its CHLs.
_AXIS_TECHNIQUE_MAP = {
    "horizontal": "audit-horizontal",
    "vertical": "audit-vertical",
    "cross-cutting": "audit-cross-cutting",
}


def _finding_category(f: dict[str, str]) -> str:
    """Sub-category of a finding within its axis: artifact type for horizontal,
    concern for cross-cutting; vertical findings have no finer category."""
    axis = f.get("axis", "")
    if axis == "horizontal":
        return f.get("type", "unknown")
    if axis == "cross-cutting":
        return f.get("concern", "unknown")
    return "vertical"


def _severity_rank(s: str) -> int:
    return {"error": 2, "warn": 1}.get(s, 0)


def _group_findings_to_chls(findings: list[dict[str, str]]) -> list[TechniqueFinding]:
    """Group warn/error audit findings by (axis, category) into ONE CHL finding
    per group with a markdown-table body, instead of one empty-body CHL per
    finding. A run that once spewed 75 truncated-title one-liners (never
    actioned) produces ~5-8 engagable CHLs.

    The title is count-free and STABLE (``Audit {axis}/{category} findings``) so
    ``create_chl_artifacts``' title-based dedup suppresses repeats across runs
    for the same group — embedding the count in the title would mint a new CHL
    every time a group's size changed and leave the old one open forever. Count
    and severity live in the body/rationale instead.
    """
    groups: dict[tuple[str, str], list[dict[str, str]]] = {}
    for f in findings:
        axis = f.get("axis", "vertical")
        groups.setdefault((axis, _finding_category(f)), []).append(f)

    out: list[TechniqueFinding] = []
    for (axis, category), items in sorted(groups.items()):
        sev = max((it["severity"] for it in items), key=_severity_rank)
        table_rows = "\n".join(
            f"| {_artifact_scope(it)} | {it['severity']} | {it['message']} |"
            for it in items
        )
        # Vertical findings have no sub-category — avoid a "vertical/vertical"
        # stutter; horizontal/cross-cutting name their type/concern.
        scope_label = "vertical" if axis == "vertical" else f"{axis}/{category}"
        title = f"Audit {scope_label} findings"
        body = (
            f"**{len(items)} finding(s)** across `{scope_label}` "
            f"(severity: {sev}).\n\n"
            f"| Scope | Severity | Finding |\n|---|---|---|\n{table_rows}\n"
        )
        out.append(TechniqueFinding(
            title=title[:100],
            rationale=f"{len(items)} {sev} finding(s) under {scope_label} "
                      f"(see body table)",
            severity=sev,
            technique=_AXIS_TECHNIQUE_MAP.get(axis, "project-audit"),
            body=body,
        ))
    return out


def run(root: Path, args: dict[str, Any]) -> int:
    root = root.resolve()
    ts = _ts()
    dry_run = bool(args.get("dry_run", False))

    specflow_dir = root / "_specflow"
    if not specflow_dir.exists():
        print(f"{YELLOW}⚠ No _specflow/ directory found{NC}")
        print("   Run 'specflow init' first.")
        return 4

    scope_info: list[str] = []

    print(f"\n{BOLD}SpecFlow Project Audit{NC}")
    print(_SEP)

    artifacts = art_lib.discover_artifacts(root)
    if not artifacts:
        print(f"{YELLOW}⚠ No artifacts found{NC}")
        return 4

    sample_pct = args.get("sample_pct") or 100
    if isinstance(sample_pct, str):
        sample_pct = int(sample_pct)
    artifacts = _sample_artifacts(artifacts, sample_pct)
    print(f"  Artifacts: {len(artifacts)}" + (f" (sampled {sample_pct}%)" if sample_pct < 100 else ""))

    # --baseline drift anchor (CHL-NONSEMVE-c16b): resolved once and shared
    # by the cross-cutting drift diff and the scope line. An unknown name
    # warns and falls back to the auto pair (accounting-not-policing: a typo
    # in the anchor never fails the audit). Anchored runs bypass the findings
    # cache both ways: the fingerprint key does not include the anchor, so a
    # cached auto-pair result could silently shadow an explicit anchor, and
    # anchored findings would poison the cache for later unanchored runs.
    baseline_anchor = (args.get("baseline") or "").strip() or None
    drift_pair, drift_anchor_warn = _resolve_drift_pair(root, baseline_anchor)
    if drift_anchor_warn:
        print(f"{YELLOW}⚠ {drift_anchor_warn}{NC}")

    cache_dir = _cache_dir(root)
    if not dry_run:
        cache_dir.mkdir(parents=True, exist_ok=True)
    if baseline_anchor:
        cache_hit, cached_findings = False, []
    else:
        cache_hit, cached_findings = _apply_fingerprint_cache(artifacts, cache_dir)

    if cache_hit:
        print(f"  Cache: project fingerprint unchanged, reusing previous findings")
        all_cached = cached_findings
        horizontal: dict[str, list[dict[str, str]]] = {}
        vertical_cached: list[dict[str, str]] = []
        cross_cutting: dict[str, list[dict[str, str]]] = {}
        for f in all_cached:
            axis = f.get("axis", "")
            if axis == "vertical":
                vertical_cached.append(f)
            elif axis == "horizontal":
                horizontal.setdefault(f.get("type", "unknown"), []).append(f)
            elif axis == "cross-cutting":
                cross_cutting.setdefault(f.get("concern", "unknown"), []).append(f)
            else:
                vertical_cached.append(f)
        horizontal = horizontal if horizontal else {}
        vertical = vertical_cached
        cross_cutting = cross_cutting if cross_cutting else {}
        cached_count = len(all_cached)
    else:
        cached_count = 0

    audit_dir = _audit_dir(root, ts)
    if dry_run:
        print(f"  Output: (dry-run — no files written)")
    else:
        audit_dir.mkdir(parents=True, exist_ok=True)
        print(f"  Output: {audit_dir.relative_to(root)}")
    print()

    if not cache_hit:
        print(f"  {CYAN}Running horizontal analysis (per artifact type)...{NC}")
        horizontal = _horizontal_analysis(artifacts)
        h_types = len(horizontal)
        print(f"  {GREEN}✓{NC} Horizontal: {h_types} type(s) with findings")

        print(f"  {CYAN}Running vertical analysis (V-model threads)...{NC}")
        vertical = _vertical_analysis(artifacts)
        print(f"  {GREEN}✓{NC} Vertical: {len(vertical)} thread finding(s)")

        quick = args.get("quick", False)
        if quick:
            cross_cutting: dict[str, list[dict[str, str]]] = {}
            print(f"  {GREEN}✓{NC} Cross-cutting: skipped (--quick mode)")
        else:
            print(f"  {CYAN}Running cross-cutting analysis...{NC}")
            cross_cutting = _cross_cutting_analysis(
                artifacts, root, drift_pair=drift_pair
            )
            cc_concerns = len(cross_cutting)
            print(f"  {GREEN}✓{NC} Cross-cutting: {cc_concerns} concern(s) analyzed")
    else:
        print(f"  {GREEN}✓{NC} Using cached findings")

    installed = standards_lib.list_installed_standards(root)
    if installed:
        scope_info.append(f"Compliance: {', '.join(installed)}")
    baselines = baseline_lib.list_baselines(root)
    if len(drift_pair) >= 2:
        drift_line = f"Baseline drift: compared {drift_pair[0]} → {drift_pair[1]}"
        if baseline_anchor and not drift_anchor_warn:
            drift_line += " (--baseline anchor)"
        scope_info.append(drift_line)
    elif baselines:
        scope_info.append(f"Baseline drift: compared N/A → {baselines[-1]}")

    if not cache_hit:
        all_findings_raw: list[dict[str, str]] = []
        for type_name, items in horizontal.items():
            for item in items:
                item["axis"] = "horizontal"
                item["type"] = type_name
                all_findings_raw.append(item)
        for item in vertical:
            item["axis"] = "vertical"
            all_findings_raw.append(item)
        for concern, items in cross_cutting.items():
            for item in items:
                item["axis"] = "cross-cutting"
                item["concern"] = concern
                all_findings_raw.append(item)
        proj_fp = _project_fingerprint(artifacts)
        # Lossless cache (CHL-344 A0): the cache stores ALL findings, so on a
        # cache hit CHL grouping works from the full set and group counts/titles
        # match fresh runs exactly. The pre-A0 cache capped at 20 findings, so a
        # cached replay dropped findings the fresh AUD stamp had already counted
        # (AUD-075 stamped 187 infos; the cached dry-run replayed 20). The stable
        # count-free title machinery stays as-is — it is about CHL dedup, not
        # truncation.
        # Anchored runs never write the cache (see the anchor block above:
        # the fingerprint key cannot represent the --baseline anchor).
        if not dry_run and not baseline_anchor:
            _save_cached_findings(cache_dir, proj_fp, all_findings_raw)

    # Chain-coverage top-line metric + prior-audit baseline for the trend line
    # (CHL-341 / CHL-344#2). Both are pure reads over the loaded artifact list,
    # so they render identically on cache hits, --quick, and --dry-run.
    chain_coverage = _chain_coverage_stats(artifacts)
    prior_aud = _select_prior_audit(artifacts)

    report = _render_report(
        ts, horizontal, vertical, cross_cutting, cached_count, len(artifacts),
        scope_info, chain_coverage=chain_coverage, prior_audit=prior_aud,
    )
    report_path = audit_dir / "report.md"
    if not dry_run:
        report_path.write_text(report, encoding="utf-8")

        sub_horiz_path = audit_dir / "subagent-horizontal.md"
        sub_horiz_lines = ["# Horizontal Analysis Details\n"]
        for type_name, items in sorted(horizontal.items()):
            sub_horiz_lines.append(f"## {type_name}\n")
            for item in items:
                sub_horiz_lines.append(f"- [{item['severity']}] {item['message']}")
            sub_horiz_lines.append("")
        sub_horiz_path.write_text("\n".join(sub_horiz_lines), encoding="utf-8")

        sub_vert_path = audit_dir / "subagent-vertical.md"
        sub_vert_lines = ["# Vertical Analysis Details\n"]
        for item in vertical:
            sub_vert_lines.append(f"- [{item['severity']}] {item['message']}")
        sub_vert_path.write_text("\n".join(sub_vert_lines), encoding="utf-8")

        sub_cross_path = audit_dir / "subagent-cross-cutting.md"
        sub_cross_lines = ["# Cross-cutting Analysis Details\n"]
        for concern, items in sorted(cross_cutting.items()):
            sub_cross_lines.append(f"## {concern}\n")
            for item in items:
                sub_cross_lines.append(f"- [{item['severity']}] {item['message']}")
            sub_cross_lines.append("")
        sub_cross_path.write_text("\n".join(sub_cross_lines), encoding="utf-8")

    all_findings = _collect_all_findings(horizontal, vertical, cross_cutting)
    errors = sum(1 for f in all_findings if f["severity"] == "error")
    escalating_warns, accounting_warns = _count_warns(all_findings)
    # Total warns (incl. accounting) for the printed summary; only escalating
    # warns drive the exit code. See _ACCOUNTING_CONCERNS for the doctrine.
    warns = escalating_warns + accounting_warns

    # AUD + CHL artifact creation and all filesystem snapshot/cache writes are
    # skipped under --dry-run: the exit code is a pure function of the in-memory
    # findings via _count_warns, so a dry run prints the identical Findings/
    # Result lines and returns the identical exit code without touching the tree.
    aud_result: dict[str, Any] = {}
    chl_count = 0
    if not dry_run:
        aud_title = f"Project Audit {ts}"
        aud_body = report
        aud_links: list[dict[str, str]] = []
        for art in artifacts[:10]:
            if art_lib.get_prefix_from_id(art.id) == "REQ":
                aud_links.append({"target": art.id, "role": "refers_to"})

        # Machine-readable summary stamp so the next audit can render honest
        # trend deltas against this run (CHL-341 / CHL-344#2). Counts mirror
        # the report's Summary table exactly; chain_coverage_pct is -1 when
        # the run has no approved STORYs to measure (n/a sentinel).
        # The A1 warn split (escalating/accounting, CHL-344) is stamped as
        # EXTRA fields alongside the baseline stamp — never folded into
        # _SUMMARY_STAMP_FIELDS, so pre-A1 priors stay full trend baselines.
        cov_covered, cov_total = chain_coverage
        stamp_pct = round(cov_covered * 100 / cov_total) if cov_total > 0 else -1
        try:
            aud_result = art_lib.create_artifact(
                root,
                artifact_type="audit",
                title=aud_title,
                status="open",
                rationale="Automated project audit",
                tags=["project-audit", "auto-generated"],
                links=aud_links,
                body=aud_body,
                review_status="unreviewed",
                summary_errors=errors,
                summary_warns=warns,
                summary_info=len(all_findings) - errors - warns,
                chain_coverage_pct=stamp_pct,
                summary_warns_escalating=escalating_warns,
                summary_warns_accounting=accounting_warns,
            )
            if aud_result.get("ok"):
                scope_info.append(f"AUD artifact: {aud_result['id']}")
        except Exception:
            pass

        if errors + warns > 0:
            warn_error_findings = [f for f in all_findings if f["severity"] in ("error", "warn")]
            target_id = aud_result.get("id", "project") if aud_result.get("ok") else "project"
            findings_typed = _group_findings_to_chls(warn_error_findings)
            chl_results = chl_lib.create_chl_artifacts(
                root, findings_typed, target_id,
                link_role="refers_to", dedup=True,
            )
            chl_count = len(chl_results)

    print()
    print(_SEP)
    if dry_run:
        print(f"  Report:   (dry-run — not written)")
    else:
        print(f"  Report:   {report_path.relative_to(root)}")
    accounting_note = (
        f" ({accounting_warns} accounting, non-escalating)" if accounting_warns else ""
    )
    print(f"  Findings: {errors} error(s), {warns} warning(s){accounting_note}, "
          f"{len(all_findings) - errors - warns} info")
    if chl_count:
        print(f"  CHL artifacts created: {chl_count}")
    print(_SEP)

    # Escalation gate: errors and STRUCTURAL (non-accounting) warns drive the
    # exit code. Accounting warns are surfaced above but cannot return exit 2,
    # so a release gate running project-audit without continue-on-error is not
    # held up by prose staleness (BP-005/006: truthful, default-to-warning).
    if errors > 0:
        print(f"  Result: {RED}ERRORS FOUND{NC}")
        return 3
    elif escalating_warns > 0:
        print(f"  Result: {YELLOW}WARNINGS FOUND{NC}")
        return 2
    else:
        print(f"  Result: {GREEN}CLEAN{NC}")
        return 0
